[features]
seeds = false
[programs.localnet]
muon_solana = "CTHYpZEvVp4TX1qgpoXkcjyNBENnZRdE36piJFQVVW1X"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/sadegh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
